stages:
  - build

build:
  stage: build
  script:
    - rm -rf /var/opt/ncs/packages/Audit-and-Remediation-Framework
    - cp -r . /var/opt/ncs/packages/Audit-and-Remediation-Framework
    - cd /var/opt/ncs/packages/Audit-and-Remediation-Framework/src
    - make
    # Test deployment
    - python /var/opt/ncs/packages/Audit-and-Remediation-Framework/python/ci-deploy.py
    # Build YANG UML documentation
    - pyang -f uml -o /var/opt/ncs/packages/Audit-and-Remediation-Framework/doc/complete_project.uml *.yang
    - pyang -f uml -o /var/opt/ncs/packages/Audit-and-Remediation-Framework/doc/project_statics.uml audit.yang input_output.yang
    - java -jar /path/to/plantuml.jar var/opt/ncs/packages/Audit-and-Remediation-Framework/doc/complete_project.uml
    - java -jar /path/to/plantuml.jar var/opt/ncs/packages/Audit-and-Remediation-Framework/doc/project_statics.uml
