#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/action-test.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module action-test.yang


class ns(object):
    hash = 294711571

    id = "http://example.com/actions"

    uri = "http://example.com/actions"

    prefix = "audit"

    audit_test = 151660234
    audit_test_ = "test"
    audit_result = 401396173
    audit_result_ = "result"
    audit_success_percent = 856009190
    audit_success_percent_ = "success_percent"
    audit_Audit = 415987372
    audit_Audit_ = "Audit"
    audit_Device_group = 32263007
    audit_Device_group_ = "Device_group"
    audit_run_time = 1050052059
    audit_run_time_ = "run_time"
    audit_disregard_out_of_sync = 193926863
    audit_disregard_out_of_sync_ = "disregard_out_of_sync"
    audit_ipv6_igmp = 1260721311
    audit_ipv6_igmp_ = "ipv6_igmp"
    audit_end_time = 102468597
    audit_end_time_ = "end_time"
    audit_remediate = 344985080
    audit_remediate_ = "remediate"
    audit_ipv6 = 1228132394
    audit_ipv6_ = "ipv6"
    audit_IPv6_igmp = 1417653996
    audit_IPv6_igmp_ = "IPv6_igmp"
    audit_start_time = 361541635
    audit_start_time_ = "start_time"
    audit_IPv6 = 1607392904
    audit_IPv6_ = "IPv6"
    actionpoint_audit = "audit"
    actionpoint_test_point = "test-point"
