#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Audits.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Audits.yang


class ns(object):
    hash = 294711571

    id = "http://example.com/actions"

    uri = "http://example.com/actions"

    prefix = "audits"

    audits_Audits = 706442599
    audits_Audits_ = "Audits"
    audits_result = 401396173
    audits_result_ = "result"
    audits_username = 870658415
    audits_username_ = "username"
    audits_input_type = 1878066786
    audits_input_type_ = "input_type"
    audits_success_percent = 856009190
    audits_success_percent_ = "success_percent"
    audits_number_audited = 897927024
    audits_number_audited_ = "number_audited"
    audits_csv = 2
    audits_csv_ = "csv"
    audits_run_time = 1050052059
    audits_run_time_ = "run_time"
    audits_device_group = 0
    audits_device_group_ = "device_group"
    audits_end_time = 102468597
    audits_end_time_ = "end_time"
    audits_remediate = 344985080
    audits_remediate_ = "remediate"
    audits_igmp = 1228497258
    audits_igmp_ = "igmp"
    audits_results = 609602154
    audits_results_ = "results"
    audits_value = 864367181
    audits_value_ = "value"
    audits_audit = 1710855485
    audits_audit_ = "audit"
    audits_inputs = 428023244
    audits_inputs_ = "inputs"
    audits_start_time = 361541635
    audits_start_time_ = "start_time"
    audits_IPv6 = 1607392904
    audits_IPv6_ = "IPv6"
    actionpoint_audit = "audit"
