#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/audit.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module audit.yang


class ns(object):
    hash = 294711571

    id = "http://example.com/actions"

    uri = "http://example.com/actions"

    prefix = "audits"

    audits_Audits = 706442599
    audits_Audits_ = "Audits"
    audits_result = 401396173
    audits_result_ = "result"
    audits_success_percent = 856009190
    audits_success_percent_ = "success_percent"
    audits_L3_ip_pim = 1191830729
    audits_L3_ip_pim_ = "L3_ip_pim"
    audits_Device_group = 32263007
    audits_Device_group_ = "Device_group"
    audits_run_time = 1050052059
    audits_run_time_ = "run_time"
    audits_end_time = 102468597
    audits_end_time_ = "end_time"
    audits_remediate = 344985080
    audits_remediate_ = "remediate"
    audits_igmp = 1228497258
    audits_igmp_ = "igmp"
    audits_audit = 1710855485
    audits_audit_ = "audit"
    audits_start_time = 361541635
    audits_start_time_ = "start_time"
    audits_IPv6 = 1607392904
    audits_IPv6_ = "IPv6"
    actionpoint_audit = "audit"
