#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/input_output.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module input_output.yang


class ns(object):
    hash = 1866487254

    id = "http://example.com/input_output"

    uri = "http://example.com/input_output"

    prefix = "input_output"

