#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ipv6_igmp.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ipv6_igmp.yang


class ns(object):
    hash = 156963000

    id = "http://example.com/ipv6_igmp"

    uri = "http://example.com/ipv6_igmp"

    prefix = "ipv6_igmp"

