#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ipv6.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ipv6.yang


class ns(object):
    hash = 1185548354

    id = "http://example.com/ipv6"

    uri = "http://example.com/ipv6"

    prefix = "ipv6"

