#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/Services.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module Services.yang


class ns(object):
    hash = 15881509

    id = "http://example.com/your_audit_name_here"

    uri = "http://example.com/your_audit_name_here"

    prefix = "Services"

    Services_Specific = 1
    Services_Specific_ = "Specific"
    Services_All = 0
    Services_All_ = "All"
