#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/your_audit_name_here.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module your_audit_name_here.yang


class ns(object):
    hash = 15881509

    id = "http://example.com/your_audit_name_here"

    uri = "http://example.com/your_audit_name_here"

    prefix = "your_audit_name_here"

