#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/your_group_name_here.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module your_group_name_here.yang


class ns(object):
    hash = 784955219

    id = "http://example.com/your_group_name_here"

    uri = "http://example.com/your_group_name_here"

    prefix = "your_group_name_here"

    your_group_name_here_device = 1
    your_group_name_here_device_ = "device"
    your_group_name_here_csv = 2
    your_group_name_here_csv_ = "csv"
    your_group_name_here_device_group = 0
    your_group_name_here_device_group_ = "device_group"
